#!/usr/bin/env ruby

require 'fileutils'
require 'json'
require 'logger'
require 'sinatra/base'
require 'yaml'

class GitNotifier
  STATE_FILE = '.git-notifier.dat'

  private

  MAPPINGS = {
    'from' => 'sender',
    'to' => 'mailinglist',
    'subject' => 'emailprefix',
    'uri' => 'repouri'
  }

  public

  def self.run(path, opts)
    args = Hash[opts.map { |k, v| [MAPPINGS[k] || k, v] }]
    success = execute(path, args)
    $logger.error('git-notifier failed') unless success
    success
  end

  private

  def self.execute(path, args = [])
    args = args.map do |k, v|
      v = v * ',' if k == 'mailinglist'
      next unless v
      ["--#{k}"] + (!!v == v ? [] : ["#{v}"]) # Ignore non-boolean values.
    end
    current = Dir.pwd()
    success = true
    Dir.chdir(path)
    begin
      $logger.debug('> git fetch origin +refs/heads/*:refs/heads/*')
      success = system('git', 'fetch', 'origin', '+refs/heads/*:refs/heads/*')
      raise "git fetch failed in #{path}" unless success
      args = args.flatten.delete_if { |x| x.nil? }
      $logger.debug("> git-notifier #{args}")
      success = system('git-notifier', *args)
      raise "git-notifier failed in #{path} with args: #{args}" unless success
    rescue Exception => e
      $logger.error(e)
    end
    Dir.chdir(current)
    success
  end
end

class GitDub
  def initialize(config)
    @notifier = config['notifier']
    @github = config['github']
    @silent_init = config['gitdub']['silent_init']

    dir = config['gitdub']['directory']
    if dir != '.'
      $logger.info("switching into working directory #{dir}")
      Dir.mkdir(dir) unless Dir.exists?(dir)
      Dir.chdir(dir)
    end
  end

  def process(push)
    opts = @notifier.clone
    url = push['repository']['url']
    user = push['repository']['owner']['name']
    repo = push['repository']['name']
    opts['link'] = "#{url}/compare/#{push['before']}...#{push['after']}"
    $logger.info("received push from #{user}/#{repo} for commits "\
                 "#{push['before'][0..5]}...#{push['after'][0..5]}")

    @github.each do |entry|
      if "#{user}\/#{repo}" =~ Regexp.new(entry['id'])
        opts.merge!(entry.reject { |k, v| k == 'id' || k == 'protocol'})
        opts['uri'] ||= url

        entry['protocol'] ||= 'git'
        remote = case entry['protocol']
                 when /git/
                   "git://github.com/#{user}/#{repo}.git"
                 when /ssh/
                   "git@github.com:#{user}/#{repo}.git"
                 when /https/
                   "https://github.com/#{user}/#{repo}.git"
                 else
                   $logger.error("invalid protocol: #{entry['protocol']}")
                   next
                 end

        dir = File.join(user, repo)
        if not Dir.exists?(dir)
          $logger.debug("> git clone --bare #{remote} #{dir}")
          if not system('git', 'clone', '--bare', remote, dir)
            $logger.error("git failed to clone repository #{user}/#{repo}")
            FileUtils.rm_rf(dir) if File.exists?(dir)
            return
          end
          # Do not keep empty user directories.
          if Dir[File.join(user, '*')].empty?
            Dir.rmdir(user)
          end
        end

        state_file = File.join(dir, GitNotifier::STATE_FILE)
        if @silent_init and not File.exists?(state_file)
          $logger.info("configuring git-notifer for silent update")
          opts['updateonly'] = true unless File.exists?(state_file)
        end

        return GitNotifier.run(dir, opts)
      end
    end
    $logger.warn("no matching repository found for #{user}/#{repo}")
  end
end

class GitDubServer < Sinatra::Base
  configure do
    set(:environment, :production)
    set(:bind, settings.bind)
    set(:port, settings.port)
  end

  get '/' do
    "Use #{request.url} as WebHook URL in your github repository settings."
  end

  post '/' do
    sources = settings.allowed_sources
    if not sources.empty? and not sources.include?(request.ip)
      $logger.info("discarding request from disallowed address #{request.ip}")
      return
    end

    if not params[:payload]
      $logger.error('received POST request with empty payload')
    else
      json = JSON.parse(params[:payload])
      if not json
        $log.error('received invalid JSON:')
        STDERR.puts(params[:payload])
      else
        STDERR.puts(JSON.pretty_generate(json)) if settings.debug_post
        # Ideally we'd use the X-Github-Event header to distinguish a ping from
        # an ordinary push. However, the 'headers' variable in Sinatra only
        # contains Content-Type, so we introspect the JSON instead.
        if json['zen']
          $logger.debug('got ping from github')
        else
          settings.gitdub.process(json)
        end
      end
    end
  end
end

def which(cmd)
  ENV['PATH'].split(File::PATH_SEPARATOR).each do |path|
    exe = "#{path}/#{cmd}"
    return exe if File.executable?(exe)
  end
  nil
end

def run(config)
  GitDubServer.set(:gitdub, GitDub.new(config))
  GitDubServer.set(:bind, config['gitdub']['bind'])
  GitDubServer.set(:port, config['gitdub']['port'])
  GitDubServer.set(:debug_post, config['gitdub']['debug'])
  GitDubServer.set(:allowed_sources, config['gitdub']['allowed_sources'])

  if not config['gitdub']['ssl']['enable']
    Sinatra.new(GitDubServer).run!
  else
    require 'webrick/https'
    require 'openssl'

    cert = File.open(config['gitdub']['ssl']['cert']).read
    key = File.open(config['gitdub']['ssl']['key']).read
    webrick_options = {
      app:            GitDubServer,
      BindAddress:    config['gitdub']['bind'],
      Port:           config['gitdub']['port'],
      Logger:         $logger,
      SSLEnable:      true,
      SSLCertificate: OpenSSL::X509::Certificate.new(cert),
      SSLPrivateKey:  OpenSSL::PKey::RSA.new(key),
      SSLCertName:    [['CN', WEBrick::Utils::getservername]]
    }

    Rack::Server.start(webrick_options)
  end
end

if __FILE__ == $0
  $logger = Logger.new(STDERR)
  $logger.formatter = proc do |severity, datetime, progname, msg|
      time = datetime.strftime('%Y-%m-%d %H:%M:%S')
      "[#{time}] #{severity}#{' ' * (5 - severity.size + 1)}gitdub | #{msg}\n"
  end

  unless which('git-notifier')
    $logger.error('could not find git-notifier in $PATH')
    exit 1
  end

  if ARGV.size() != 1
    STDERR.puts "usage: #{$0} <config.yml>"
    exit 1
  end

  file = File.absolute_path(ARGV[0])
  config = YAML.load_file(file)

  sinatra = Thread.new { run(config) }

  if config['gitdub']['monitor'] > 0
    last_modified = Time.at(0)
    loop do
      mtime = File.mtime(file)
      if mtime > last_modified
        last_modified = mtime
        $logger.info("re-reading configuration file")
        config = YAML.load_file(file)
        GitDubServer.set(:gitdub, GitDub.new(config))
        GitDubServer.set(:debug_post, config['gitdub']['debug'])
        GitDubServer.set(:allowed_sources, config['gitdub']['allowed_sources'])
        break if config['gitdub']['monitor'] == 0
      end

      break unless sinatra.alive?
      sleep(config['gitdub']['monitor'])
    end
  end

  sinatra.join
end
